# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: demo.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'demo.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x05unary\"\t\n\x07GetNone\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\"r\n\x0fGetUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x11\n\tuser_name\x18\x02 \x01(\t\x12\x12\n\nuser_email\x18\x03 \x01(\t\x12\x12\n\nuser_roles\x18\x04 \x01(\t\x12\x13\n\x0buser_status\x18\x05 \x01(\t2\xd1\x02\n\x05Users\x12.\n\x0cGetNoneUnary\x12\x0e.unary.GetNone\x1a\x0e.unary.GetNone\x12=\n\x0cGetUserUnary\x12\x15.unary.GetUserRequest\x1a\x16.unary.GetUserResponse\x12\x46\n\x13GetUserClientStream\x12\x15.unary.GetUserRequest\x1a\x16.unary.GetUserResponse(\x01\x12\x46\n\x13GetUserServerStream\x12\x15.unary.GetUserRequest\x1a\x16.unary.GetUserResponse0\x01\x12I\n\x14GetUserBidirectional\x12\x15.unary.GetUserRequest\x1a\x16.unary.GetUserResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETNONE']._serialized_start=21
  _globals['_GETNONE']._serialized_end=30
  _globals['_GETUSERREQUEST']._serialized_start=32
  _globals['_GETUSERREQUEST']._serialized_end=65
  _globals['_GETUSERRESPONSE']._serialized_start=67
  _globals['_GETUSERRESPONSE']._serialized_end=181
  _globals['_USERS']._serialized_start=184
  _globals['_USERS']._serialized_end=521
# @@protoc_insertion_point(module_scope)
